use_frameworks!

platform :ios, '10.0'
#https://zhuanlan.zhihu.com/p/128452187
target 'JLTools_Example' do
  pod 'JLTools', :path => '../'

  target 'JLTools_Tests' do
    inherit! :search_paths

    
  end
end
